-- ================================================================
-- v15 MLS Blog Content Migration
--
-- Extends blog_posts into the single source of truth for the
-- production MLS-powered blog (public URL /blog). Articles are
-- generated by src/modules/blog/services/blogGeneratorService.js
-- directly from live MLS Grid listing data.
--
--   source_type   — provenance: 'mls' (public blog) vs 'agent'
--   status        — 'published' | 'draft' | 'archived'
--   category      — Market Trends / Neighborhood Guides / New
--                   Listings / Luxury Homes / Investment
--   city/county/state/neighborhood — geo facets + SEO + routing
--                   (/blog/city/:city)
--   listing_key   — MLS listing that produced the article (unique)
--   read_time     — minutes to read (computed from content length)
--   published_at  — used for "Newest" sorting + sitemap
--   meta_title/meta_description — SEO (fallback to title/excerpt)
--   tags[]        — Tag pills from real listing attributes
--   metrics JSONB — views/likes/shares + listing JSON snapshot
--   author_name   — "Vasu Realty" / "Vasu Realty Agents"
--   featured      — editorial pin for the hero slot
--
-- All statements are idempotent (ADD COLUMN IF NOT EXISTS /
-- CREATE INDEX IF NOT EXISTS) and safe to re-run.
-- ================================================================

-- ---- provenance + lifecycle -------------------------------------------------
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS source_type VARCHAR(20) NOT NULL DEFAULT 'mls';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS status VARCHAR(20) NOT NULL DEFAULT 'published';

-- ---- content + editorial facets ---------------------------------------------
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS category VARCHAR(100);
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS city VARCHAR(150);
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS county VARCHAR(150);
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS state VARCHAR(10);
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS neighborhood VARCHAR(200);
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS listing_key VARCHAR(255);
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS read_time INTEGER NOT NULL DEFAULT 1;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;

-- ---- SEO ---------------------------------------------------------------------
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS meta_title TEXT;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS meta_description TEXT;

-- ---- tags + metrics + attribution -------------------------------------------
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS tags TEXT[] NOT NULL DEFAULT '{}';
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS metrics JSONB NOT NULL DEFAULT '{}'::jsonb;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS author_name VARCHAR(255);
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS featured BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE blog_posts ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW();

-- ---- indexes (idempotent) ----------------------------------------------------
CREATE INDEX IF NOT EXISTS idx_blog_posts_status ON blog_posts(status);
CREATE INDEX IF NOT EXISTS idx_blog_posts_source_type ON blog_posts(source_type);
CREATE INDEX IF NOT EXISTS idx_blog_posts_status_source ON blog_posts(status, source_type);
CREATE INDEX IF NOT EXISTS idx_blog_posts_category ON blog_posts(category);
CREATE INDEX IF NOT EXISTS idx_blog_posts_city ON blog_posts(city);
CREATE INDEX IF NOT EXISTS idx_blog_posts_county ON blog_posts(county);
CREATE INDEX IF NOT EXISTS idx_blog_posts_published_at ON blog_posts(published_at DESC);
CREATE INDEX IF NOT EXISTS idx_blog_posts_tags ON blog_posts USING GIN (tags);
CREATE UNIQUE INDEX IF NOT EXISTS idx_blog_posts_listing_key ON blog_posts(listing_key) WHERE listing_key IS NOT NULL;

-- Keep back-compat flag in sync with status for anything that still reads
-- blog_posts.published (no such consumer exists yet, but cheap insurance).
UPDATE blog_posts SET published = (status = 'published') WHERE published IS DISTINCT FROM (status = 'published');
